# Generated by Django 5.2.13 on 2026-04-20 12:36

import leads.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('service_interest', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('industry', models.CharField(max_length=140)),
                ('project_type', models.CharField(choices=[('company_website', 'Company Website'), ('web_application', 'Web Application'), ('mobile_application', 'Mobile Application'), ('ai_automation', 'AI Automation'), ('whatsapp_automation', 'WhatsApp Automation'), ('payment_integration', 'Payment Integration'), ('dashboard_analytics', 'Dashboard / Analytics'), ('custom_business_system', 'Custom Business System'), ('other', 'Other')], max_length=60)),
                ('budget_range', models.CharField(choices=[('below_1m', 'Below TZS 1M'), ('tzs_1m_3m', 'TZS 1M - 3M'), ('tzs_3m_7m', 'TZS 3M - 7M'), ('tzs_7m_15m', 'TZS 7M - 15M'), ('tzs_15m_plus', 'TZS 15M+'), ('not_sure', 'Not sure yet')], max_length=40)),
                ('timeline', models.CharField(max_length=140)),
                ('message', models.TextField(verbose_name='Project description')),
                ('has_existing_system', models.BooleanField(default=False)),
                ('has_existing_designs', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, upload_to='lead-attachments/', validators=[leads.validators.validate_attachment])),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
