# Generated by Django 5.2.13 on 2026-04-20 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('tagline', models.CharField(max_length=220)),
                ('summary', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('key_features', models.TextField(help_text='One feature per line.')),
                ('tech_stack', models.TextField(help_text='One technology or approach per line.')),
                ('industry', models.CharField(max_length=160)),
                ('featured_image', models.ImageField(blank=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('seo_title', models.CharField(max_length=180)),
                ('seo_description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
